
server:
  port: 8090
  url: "http://localhost:8090"

logging:
  level:
    com.example.pongdang: DEBUG
    org.springframework: DEBUG
    root: INFO
    org.hibernate.SQL: DEBUG
    # springboot 3.x hibernate 6버전 이상 바인딩된 파라미터 로그 설정
    org.hibernate.orm.jdbc.bind: TRACE

file:
  upload-dir: C:/pongdang-server/uploads # 이미지 파일 업로드 경로(로컬)

# H2 Database
spring:
  application:
    name: pongdang
  datasource:
    url: jdbc:h2:file:./data/testdb
    drvierClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # SQL 쿼리에 주석 추가
        highlight_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB   # ✅ 업로드 가능한 파일 크기 (개별 파일)
      max-request-size: 100MB # ✅ 전체 요청 크기 (파일 여러 개 포함)
