server:
  port: 8090
  url: "https://pongdangserver.shop"

spring:
  datasource:
    url: jdbc:mysql://config-db.cvcw2cca2r2e.ap-northeast-2.rds.amazonaws.com:3306/pongdangDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gayhoon
    password: a9a1a7a4

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true

jwt:
  secret: "b0j48K7h6YvB5pN8tQ2m3X4rW1zT9fG7"

file:
  upload-dir: /var/lib/jenkins/workspace/pongdangserver/uploads

kakao:
  redirect-uri: "https://www.pongdangserver.shop/auth/callback"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
