spring:
  config:
    activate:
      on-profile: prod  # 'prod' 프로필에서만 적용

server:
  url: "http://43.201.88.18:80"
  port: 80
  address: 0.0.0.0  # 외부 접근 가능하도록 설정

file:
  upload-dir: "/home/ubuntu/pongdang-server/uploads"  # 리눅스 환경에 맞게 변경

datasource:
  url: jdbc:mysql://prod-db-instance:3306/pongdang  # 운영 DB
  driverClassName: com.mysql.cj.jdbc.Driver
  username: admin
  password: "securepassword"

jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
