
server:
  port: 8090
  url: "http://localhost:8090" # 로컬인 경우 [체인지]
#  url: "https://pongdangserver.shop" # 운영인 경우 [체인지]

logging:
  level:
    com.example.pongdang: DEBUG
    org.springframework: DEBUG
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

file:
  upload-dir: C:/pongdang-server/uploads # 이미지 파일 업로드 경로(로컬)

jwt:
  secret: "b0j48K7h6YvB5pN8tQ2m3X4rW1zT9fG7"

# H2 Database(시도) 흠 ㄹ3
spring:
  application:
    name: pongdang
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:./data/testdb
    drvierClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # SQL 쿼리에 주석 추가
        highlight_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB   # 업로드 가능한 파일 크기 (개별 파일)
      max-request-size: 100MB # 전체 요청 크기 (파일 여러 개 포함)

kakao:
#  redirect-uri: "https://www.pongdangserver.shop/auth/callback"
  redirect-uri: "http://localhost:3000/auth/callback"