spring:
  application:
    name: pongdang
  profiles:
    active: local  # 기본 실행 프로필 (로컬 개발)

jwt:
  secret: "b0j48K7h6YvB5pN8tQ2m3X4rW1zT9fG7"

logging:
  level:
    com.example.pongdang: DEBUG
    org.springframework: DEBUG
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

servlet:
  multipart:
    enabled: true
    max-file-size: 50MB   # 업로드 가능한 파일 크기 (개별 파일)
    max-request-size: 100MB # 전체 요청 크기 (파일 여러 개 포함)
