
server:
  port: 8090

# H2 Database
spring:
  application:
    name: pongdang
  datasource:
    url: jdbc:h2:file:./data/testdb
    drvierClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true